language: python

python:
  - "2.7_with_system_site_packages"

install:
  - "sudo apt-get install python-pil python-reportlab"
  - "pip install -r requirements.txt"

script:
  - "python manage.py test"
